-- Exercise the actual cart parser/importer, save namespace and sealed mod plan.
package.path='./?.lua;./?/init.lua;'..package.path
love=require('tests.love_stub')
require('src.core.GameVersion').set('emerald')
local M=require('src.carts.CartManifest');local Store=require('src.carts.CartStore')
local Save=require('src.core.SaveData');local Update=require('src.mods.ModUpdate')
local f=assert(io.open(assert(arg[1]),'rb'));local bytes=f:read('*a');f:close()
local cart=assert(M.decode(bytes));assert(M.publishable(cart))
assert(cart.id=='pokemon_heart_soul'and cart.base=='emerald'and cart.seal=='sealed')
assert(cart.version==arg[4]);assert(cart.mods[1].version==arg[3]);assert(cart.mods[1].sha256==arg[2])
assert(cart.mods[1].source=='github'and cart.mods[1].repo=='TheEelYT/g1r-hns')
assert(M.modEnabled(cart.mods[1]));assert(#cart.mods==1 and cart.load_order[1]=='hns_exploration')
local label=assert(M.labelArtBytes(cart));assert(#label==770595 and label:sub(1,8)==M.PNG_SIGNATURE)
assert(M.hash(cart)==M.hash(assert(M.decode(M.encode(cart)))))
local files={};local fs={read=function(p)return files[p]end,write=function(p,b)files[p]=b;return true end,createDirectory=function()return true end,getInfo=function(p)return files[p]and {type='file'}end}
love.filesystem=fs;Save.resetSlotState()
local old=assert(M.parse({id=cart.id,title=cart.title,author='Unknown',version='1.0.0',base='emerald',shell=cart.shell,seal='sealed',mods={{id='hns_exploration',source='local',version='0.7.1'}}}))
assert(Store.install(M.encode(old),fs));Save.setCart(old.id,M.hash(old))
local slot=assert(Save.createCartSlot(old.id))
assert(Store.install(bytes,fs),'release cart upgrades the existing 1.0.0 local cart')
Save.setCart(cart.id,M.hash(cart))
assert(Save.listCartSlots(cart.id)[1].id==slot,'the existing cart slot survives the GitHub upgrade')
assert(#Save.listCartSlots(cart.id)==1);assert(#Save.listCartSlots('other_cart')==0)
assert(Save.getCart()==cart.id and Save.getCartHash()==M.hash(cart))
local picked=assert(Update.pickZipAsset({{name='pokemon_heart_soul-'..cart.version..'.g1rcart'},{name='hns_exploration-'..arg[3]..'.zip',browser_download_url='fixture'}},'hns_exploration',arg[3]))
assert(picked.url=='fixture','GitHub pin resolves the versioned mod ZIP')
local Loader=require('src.mods.Loader')
local plan=Loader.planCart(cart,{{id='hns_exploration',version=arg[3]}},false)
assert(plan.enforced and plan.seal=='sealed')
assert(not Loader.pinTogglable(plan,cart.mods[1]),'sealed cart disables edits to its active mod')
print('Cart release: native parse/roundtrip/import, 1.0.0 upgrade, exact GitHub pin, embedded label, isolated saves and sealed mod edits pass')
